[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

upload_port = /dev/ttyACM0

build_flags = 
    -D ARDUINO_USB_MODE=1          ; USB device mode, keep HID behavior minimal
    -D ARDUINO_USB_CDC_ON_BOOT=0   ; Disable USB CDC serial console to avoid debug enumeration
    -D BOARD_HAS_PSRAM

lib_deps =
    links2004/WebSockets @ ^2.4.1